config/routes.rb
Rails.application.routes.draw do

  root "dashboard#index"

  resources :channels, only: [] do
    resources :standups, only: :index
  end

  resources :users, only: [ :index, :update ]
  resources :settings, only: [ :index, :update, :create ]

  namespace :api do
    resources :standups, only: [] do
      get :start, on: :collection
    end

    get 'start' => 'standups#start'
  end

end

app/models/standup.rb
# == Schema Information
#
# Table name: standups
#
#  id                 :integer          not null, primary key
#  yesterday          :text
#  today              :text
#  conflicts          :text
#  created_at         :datetime
#  updated_at         :datetime
#  channel_id         :integer
#  user_id            :integer
#  order              :integer          default(1)
#  state              :string
#  auto_skipped_times :integer          default(0)
#  reason             :string
#

class Standup < ActiveRecord::Base

  IDLE          = 'idle'
  ACTIVE        = 'active'
  ANSWERING     = 'answering'
  DONE          = 'done'
  NOT_AVAILABLE = 'not_available'
  VACATION      = 'vacation'

  MAXIMUM_AUTO_SKIPPED_TIMES = 2

  belongs_to :user
  belongs_to :channel

  validates :user_id, :channel_id, presence: true

  scope :for, -> user_id, channel_id { where(user_id: user_id, channel_id: channel_id) }
  scope :today, -> { where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day) }
  scope :by_date, -> date { where(created_at: date.at_midnight..date.next_day.at_midnight) }

  scope :in_progress, -> { where(state: [ACTIVE, ANSWERING]) }
  scope :active, -> { where(state: ACTIVE) }
  scope :pending, -> { where(state: IDLE) }
  scope :completed, -> { where(state: [DONE, NOT_AVAILABLE, VACATION]) }

  scope :sorted, -> { order(order: :asc) }

  delegate :slack_id, :full_name, to: :user, prefix: true
  delegate :slack_id, to: :channel, prefix: true

  state_machine initial: :idle do

    event :init do
      transition from: :idle, to: :active
    end

    event :skip do
      transition from: :active, to: :idle
    end

    event :start do
      transition from: :active, to: :answering
    end

    event :edit do
      transition from: :done, to: :answering
    end

    event :not_available do
      transition from: :active, to: :not_available
    end

    event :vacation do
      transition from: :active, to: :vacation
    end

    event :finish do
      transition from: :answering, to: :done
    end

    before_transition on: :skip do |standup, _|
      standup.order= (standup.channel.today_standups.maximum(:order) + 1) || 1
    end

  end

  class << self

    # @param [Integer] user_id.
    # @param [Integer] channel_id.
    #
    # @return [Standup]
    def create_if_needed(user_id, channel_id)
      return if User.find(user_id).bot?

      standup = Standup.today.for(user_id, channel_id).first_or_initialize

      standup.save

      standup
    end

  end

  # @return [Boolean]
  def completed?
    done? || vacation? || not_available?
  end

  # @return [Boolean]
  def in_progress?
    active? || answering?
  end

  def question_for_number(number)
    case number
    when 1 then Time.now.wday == 4 ? "1. What did you do on Friday?" : "1. What did you do yesterday?"
    when 2 then "2. What are you working on today?"
    when 3 then "3. Is there anything standing in your way?"
    end
  end

  def current_question
    if self.yesterday.nil?
      Time.now.wday == 1 ? "<@#{self.user.slack_id}> 1. What did you do on Friday?" : "<@#{self.user.slack_id}> 1. What did you do yesterday?"

    elsif self.today.nil?
      "<@#{self.user.slack_id}> 2. What are you working on today?"

    elsif self.conflicts.nil?
      "<@#{self.user.slack_id}> 3. Is there anything standing in your way?"
    end
  end

  def process_answer(answer)
    answer = replace_slack_ids_for_names(answer)

    if self.yesterday.nil?
      self.update_attributes(yesterday: answer)

    elsif self.today.nil?
      self.update_attributes(today: answer)

    elsif self.conflicts.nil?
      self.update_attributes(conflicts: answer)
    end

    if self.yesterday.present? && self.today.present? && self.conflicts.present?
      self.finish!
    end
  end

  def delete_answer_for(question)
    case question
    when 1
      self.update_attributes(yesterday: nil)
    when 2
      self.update_attributes(today: nil)
    when 3
      self.update_attributes(conflicts: nil)
    end
  end

  # Returns the current status of the standup.
  #
  # @return [String]
  def status
    if idle?
      "<@#{self.user.slack_id}> is in the queue waiting to do the standup."
    elsif active?
      "<@#{self.user.slack_id}> needs to answer if wants to do the standup."
    elsif answering?
      if yesterday.nil?
        "<@#{self.user.slack_id}> is answering what did yesterday."
      elsif today.nil?
        "<@#{self.user.slack_id}> is answering what's planning to do today."
      else
        "<@#{self.user.slack_id}> is answering if has any conflicts."
      end
    elsif completed?
      if vacation?
        "<@#{self.user.slack_id}> is on vacation."
      elsif not_available?
        "<@#{self.user.slack_id}> is not available."
      else
        "<@#{self.user.slack_id}> already did the standup."
      end
    end
  end

  private

  # Replaces all the Slack user ids with the name of those users.
  #
  # @param [String] text.
  # @return [String]
  def replace_slack_ids_for_names(text)
    return text if (user_ids = text.scan(/\<@(.*?)\>/)).blank?

    user_ids.each do |user_id|
      user = User.find_by_slack_id(user_id.first)

      text.gsub!("<@#{user_id.flatten.first}>", (user ? user.full_name : "User Not Available"))
    end

    text
  end

  def settings
    Setting.first
  end

end

app/controllers/api/standups_controller.rb
require 'standupbot/client'
require 'standupbot/slack/channel'

class Api::StandupsController < Api::BaseController

  before_filter :populate_channel_id_if_given_channel_name

  respond_to :html, :text, only: :start

  # GET /api/standups/start
  def start
    @client = Standupbot::Client.new(params[:channel_id])

    if @client.valid?
      @client.start!
    else
      @errors = @client.errors
    end

    respond_with(@errors)
  end

  private

  # If the API receives the channel name instead of the channel slack id,
  #   we need to get the slack id before starting a new session.
  #
  def populate_channel_id_if_given_channel_name
    if params[:channel_id].blank? && params[:channel_name].present?
      channel = Standupbot::Slack::Channel.by_name(params[:channel_name])

      params[:channel_id] = channel.try(:[], 'id')
    end
  end

end

app/controllers/standups_controller.rb
class StandupsController < ApplicationController

  respond_to :html

  # GET /channels/:channel_id/standups
  def index
    @date     = Date.parse(params[:date]) rescue Date.today
    @channel  = Channel.find(params[:channel_id])
    @standups = @channel.standups.by_date(@date).completed.sort_by { rand }

    respond_with(@standups)
  end

end

app/views/standups/index.html.haml
%h2
  %b= "##{@channel.name}"

%br

.row.standup-date
  .col-md-6.date
    %h2
      %b= @date.strftime("%A")
      = @date.strftime('%d')
      = @date.strftime('%b')
  .col-md-6.date-picker
    %a.previous-date
      = link_to 'Previous Day', channel_standups_url(@channel, date: @date.prev_day)
    - if @date == Date.today
      |
      %a.not-active Today
    - else
      %a.todays-date{ href: channel_standups_url(@channel) } Today
      %a.next-date
        = link_to 'Next Day', channel_standups_url(@channel, date: @date.next_day)

.masonry-container.row.clearfix
  - if @standups.empty?
    .alert.alert-warning
      There are no standups for this day.

  - else
    - @standups.each do |standup|
      .col-md-4.standup-card.item
        .standup-card-wrap
          .name-section.section.clearfix
            .row
              .col-lg-3.avatar
                = image_tag(standup.user.avatar_url)
              .col-lg-9
                %h2
                  = standup.user.full_name

          - if standup.vacation? || standup.not_available?
            .vacation.section
              %br
              .text-center
                %b
                  - if standup.vacation?
                    Vacation
                  - else
                    Not Available
                = " #{standup.reason}" if standup.reason.present?

          - else
            .yesterday-section.section
              %h2 What I worked on yesterday:
              %ul
                - if standup.yesterday.present?
                  - standup.yesterday.split(/\n/).each do |text|
                    %li= emojify(text)

            .today-section.section
              %h2 What I am working on today:
              %ul
                - if standup.today.present?
                  - standup.today.split(/\n/).each do |text|
                    %li= emojify(text)

            .blocks-section.section
              %h2 Anything in my way:
              %ul
                - if standup.conflicts.present?
                  - standup.conflicts.split(/\n/).each do |text|
                    %li= emojify(text)